#!/bin/sh

### BEGIN INIT INFO
# Provides:          myservice
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Put a short description of the service here
# Description:       Put a long description of the service here
### END INIT INFO

### DEBIAN style initscript

#Change this
DIR=/directory/of/dumbdns    #Directory of dumbdns
DAEMON=${DIR}/dumbdns.py     #dumbdns script
DAEMON_NAME=dumbdns

DAEMON_USER=root

PID_FILE=/var/run/${DAEMON_NAME}.pid

. /lib/lsb/init-functions

do_start() {
   start-stop-daemon --start --background --pidfile $PID_FILE --make-pidfile --$user $DAEMON_USER --chuid $DAEMON_USER --startas $DAEMON
}
do_stop() {
   start-stop-daemon --stop --pidfile $PID_FILE --retry 5
}

case "$1" in 
   start)
      do_start
      ;; 
   stop)
      do_stop
      ;; 
   restart|reload|force-reload) 
      do_stop
      sleep 0.2
      do_start
      ;;

   status)
      status_of_proc "$DAEMON_NAME" "$DAEMON" && exit 0 || exit $?
      ;;

   *)
   echo "Usage: /etc/init.d/$DAEMON_NAME {start|stop|restart|status}"
      exit 1 
      ;; 
esac 

exit 0
